# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=200)),
                ('vehicle_id', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
                ('start_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TripCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('direction', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
