# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtrip',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
