# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_completedtrip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtrip',
            name='end_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='completedtrip',
            name='start_time',
            field=models.CharField(max_length=200),
        ),
    ]
